[project]
name = 'Workchain'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Workchain]
path = 'contracts/Workchain.clar'
clarity_version = 3
epoch = 3.1
[contracts.ContractAmendments]
path = 'contracts/ContractAmendments.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
